import "./styles/globals.css";
import "react-toastify/dist/ReactToastify.css";

import Providers from "@/app/providers";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "./components/footer";
import Header from "./components/header";
import ContactInfo from "./components/contactInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auto Live Event Photos",
  description: "Generated by Gallery using NextJS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ContactInfo />
          <Header />

          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
